void foo(void) { }
void bar(void) { }
void baz(void) { }
void stuff(void) { }
void thingy(void) { }
void foo_bar_baz(void) { }
void bar_baz_foo(void) { }
void StuffThingy(void) { }
void ThingyStuff(void) { }
